TetraBot: WorldInfo Class Reference
WorldInfo Class Reference
Classe décrivant les limites du monde dans lequel la physique s'applique ainsi que la gravité. La zone où la physique est présente est définie par deux points.
#include <WorldInfo.h>
Public Member Functions
WorldInfo (Vector3Gen *min, Vector3Gen *max, Vector3Gen *gravity)
Constructeur créant une définition du monde.
const Vector3Gen * getMin () const
getter
const Vector3Gen * getMax () const
getter
const Vector3Gen * getGravity () const
getter
Protected Attributes
Vector3Gen * max
Vector3Gen * gravity
Detailed Description
Classe décrivant les limites du monde dans lequel la physique s'applique ainsi que la gravité. La zone où la physique est présente est définie par deux points.
Definition at line 16 of file WorldInfo.h.
Constructor & Destructor Documentation
WorldInfo::WorldInfo (Vector3Gen * min, Vector3Gen * max, Vector3Gen * gravity)
Constructeur créant une définition du monde.
< gravity : Vecteur définissant la gravité.
Parameters:
[min] : Point représentant la limite inférieur du monde dans lequel la physique doit s'appliquer.
[max] : Point représentant la limite supérieur du monde dans lequel la physique doit s'appliquer.
[gravity] : Vecteur définissant la gravité du monde.
Definition at line 3 of file WorldInfo.cpp.
Member Function Documentation
const Vector3Gen * WorldInfo::getGravity () const
getter
Returns:
Retourne la gravité sous la forme d'un vecteur.
Definition at line 18 of file WorldInfo.cpp.
References gravity.
Referenced by PhysicWorld::PhysicWorld().
const Vector3Gen * WorldInfo::getMax () const
getter
Returns:
Borne supérieur du monde.
Definition at line 14 of file WorldInfo.cpp.
References max.
Referenced by PhysicWorld::PhysicWorld().
const Vector3Gen * WorldInfo::getMin () const
getter
Returns:
Borne inférieur du monde.
Definition at line 10 of file WorldInfo.cpp.
Referenced by PhysicWorld::PhysicWorld().
Member Data Documentation
Vector3Gen* WorldInfo::gravity [protected]
< max : Point représentant la limite supérieur dans laquelle la physique doit s'appliquer.
Definition at line 21 of file WorldInfo.h.
Referenced by getGravity().
Vector3Gen* WorldInfo::max [protected]
< min : Point représentant la limite inférieur dans laquelle la physique doit s'appliquer.
Definition at line 20 of file WorldInfo.h.
Referenced by getMax().
The documentation for this class was generated from the following files:
WorldInfo.h
WorldInfo.cpp