TetraBot: RobotWheels Class Reference
RobotWheels Class Reference
Robot bi-pyramidale dans lequel les deux pyramides sont liées entre elles par un piston. Le robot est composé de pistons et de noeuds sphériques hormis pour les deux noeuds des sommets des piramides, qui sont cylindriques. Par ailleur, les pistons ont des caractéristiques différentes les uns des autres.
#include <RobotWheels.h>
Public Member Functions
RobotWheels (btDynamicsWorld *world, const btVector3 &posInit)
Constructeur du robot.
btVector3 getCenterOfMassPosition ()
Méthode calculant le centre de masse du robot.
void translate (const btVector3 &to)
Permet de faire une translation sur le robot.
Detailed Description
Robot bi-pyramidale dans lequel les deux pyramides sont liées entre elles par un piston. Le robot est composé de pistons et de noeuds sphériques hormis pour les deux noeuds des sommets des piramides, qui sont cylindriques. Par ailleur, les pistons ont des caractéristiques différentes les uns des autres.
Definition at line 24 of file RobotWheels.h.
Constructor & Destructor Documentation
RobotWheels::RobotWheels (btDynamicsWorld * world, const btVector3 & posInit)
Constructeur du robot.
Parameters:
[world] : définition du monde selon le moteur physique Bullet.
[posInit] : position initiale du robot: une translation est donc effectuée pour que le robot soit précisement à ce point.
Definition at line 3 of file RobotWheels.cpp.
References PhysicRobot::Arcs, EDGE_VELOCITY, PhysicPiston::getConeA(), PhysicPiston::getConeB(), PhysicPiston::lock(), M_PI, M_PI_2, M_PI_4, NODE_RADIUS, NODE_WEIGHT, PhysicRobot::Sommets, and translate().
Member Function Documentation
btVector3 RobotWheels::getCenterOfMassPosition () [virtual]
Méthode calculant le centre de masse du robot.
Returns:
Centre de masse du robot.
Implements PhysicRobot.
Definition at line 87 of file RobotWheels.cpp.
References PhysicRobot::Sommets.
Referenced by translate().
void RobotWheels::translate (const btVector3 & to) [virtual]
Permet de faire une translation sur le robot.
Parameters:
[to] : point représentant la destination du robot. Une fois la méthode exécutée, le centre de masse du robot sera situé au point [to].
Implements PhysicRobot.
Definition at line 100 of file RobotWheels.cpp.
References getCenterOfMassPosition(), and PhysicRobot::Sommets.
Referenced by RobotWheels().
The documentation for this class was generated from the following files:
RobotWheels.h
RobotWheels.cpp