TetraBot: GLTetraRendering Class Reference
GLTetraRendering Class Reference
Gere le rendu graphique en mode debug (OpenGL).
#include <GLTetraRendering.h>
Public Member Functions
GLTetraRendering ()
Constructeur de la classe GLTetraRendering pour initialiser le rendu.
void initPhysics ()
Methode pour initialiser le monde bullet et pour creer un robot.
void initModel ()
Methode pour initialiser le model.
void drawSliders ()
Méthode permettant d'afficher à l'écran les repères internes des objets Bullet (rigidBody). Les repères sont en bleu/vert/rouge.
void drawSliderConstraint (btSliderConstraint *constraint)
Méthode permettant d'afficher en blanc la contrainte linéaire passée en paramètre.
virtual void clientMoveAndDisplay ()
Méthode effectuant le rendu de l'application.
virtual void displayCallback ()
Methode affichant les contraintes linéaires des pistons du robot.
void specialKeyboard (int key, int x, int y)
Methode pour interagir avec bullet (touches clavier Fn).
void keyboardCallback (unsigned char key, int x, int y)
Methode pour interagir avec bullet (touches clavier).
void renderme ()
Methode de rendu pour l'affichage de l'application.
Static Public Member Functions
static Application * Create ()
Methode créant l'application de manière statique.
Public Attributes
ActionPiston * action [6]
PhysicWorld * world
RobotTetra * robot
btRigidBody * bodyCube
btRigidBody * bodyPave
Detailed Description
Gere le rendu graphique en mode debug (OpenGL).
Definition at line 44 of file GLTetraRendering.h.
Constructor & Destructor Documentation
GLTetraRendering::GLTetraRendering ()
Constructeur de la classe GLTetraRendering pour initialiser le rendu.
Destructeur de la classe GLTetraRendering.
Definition at line 10 of file GLTetraRendering.cpp.
References action.
Referenced by Create().
Member Function Documentation
void GLTetraRendering::drawSliderConstraint (btSliderConstraint * constraint)
Méthode permettant d'afficher en blanc la contrainte linéaire passée en paramètre.
Parameters:
[constraint] : Contrainte linéaire à afficher.
void GLTetraRendering::keyboardCallback (unsigned char key, int x, int y)
Methode pour interagir avec bullet (touches clavier).
Parameters:
key : touche du clavier
x : position x
y : position y
Definition at line 281 of file GLTetraRendering.cpp.
References bodyPave, RobotTetra::Deplacement(), PhysicNoeud::getBody(), robot, and PhysicRobot::Sommets.
void GLTetraRendering::specialKeyboard (int key, int x, int y)
Methode pour interagir avec bullet (touches clavier Fn).
Parameters:
key : touche du clavier
x : position x
y : position y
Definition at line 413 of file GLTetraRendering.cpp.
References PhysicRobot::Arcs, bodyCube, RobotTetra::bodyCube, RobotTetra::marcherRobot(), RobotTetra::maxiRobot(), RobotTetra::nanoRobot(), robot, and AlgoGenTetra::run().
Member Data Documentation
ActionPiston* GLTetraRendering::action[6]
tableau des actions des pistons
Definition at line 59 of file GLTetraRendering.h.
Referenced by GLTetraRendering().
btRigidBody* GLTetraRendering::bodyCube
bodyCube : indicateur de la position cible
Definition at line 65 of file GLTetraRendering.h.
Referenced by initPhysics(), and specialKeyboard().
btRigidBody* GLTetraRendering::bodyPave
bodyPave : indicateur de piston
Definition at line 67 of file GLTetraRendering.h.
Referenced by initPhysics(), and keyboardCallback().
RobotTetra* GLTetraRendering::robot
robot qui est dans le monde bullet
Definition at line 63 of file GLTetraRendering.h.
Referenced by clientMoveAndDisplay(), displayCallback(), initPhysics(), keyboardCallback(), and specialKeyboard().
PhysicWorld* GLTetraRendering::world
le monde physique
Definition at line 61 of file GLTetraRendering.h.
The documentation for this class was generated from the following files:
GLTetraRendering.h
GLTetraRendering.cpp