TetraBot: PhysicWorld Class Reference
PhysicWorld Class Reference
Représentation du monde et du terrain.
#include <PhysicWorld.h>
Public Member Functions
PhysicWorld (const WorldInfo info)
Constructeur définissant le monde selon le moteur physique Bullet sans terrain. Pour ajouter un terrain dans le monde, utiliser la méthode initGround.
void initGround (const char *filename)
Méthode permettant de créer un terrain (objet rigide de masse nulle selon le moteur physique Bullet) à partir d'une meshe WaveFrontObject (.obj).
void setGravite (const btVector3 &newGravite)
setter permettant d'affecter au monde une nouvelle gravitée, remplacant l'ancienne.
btVector3 getGravite ()
getter
Detailed Description
Représentation du monde et du terrain.
Definition at line 27 of file PhysicWorld.h.
Constructor & Destructor Documentation
PhysicWorld::PhysicWorld (const WorldInfo info)
Constructeur définissant le monde selon le moteur physique Bullet sans terrain. Pour ajouter un terrain dans le monde, utiliser la méthode initGround.
Parameters:
[info] : classe contenant les informations necessaires à la création du monde à savoir la gravité et les limites du monde physique virtuel.
Definition at line 3 of file PhysicWorld.cpp.
References WorldInfo::getGravity(), WorldInfo::getMax(), and WorldInfo::getMin().
Member Function Documentation
btVector3 PhysicWorld::getGravite ()
getter
Returns:
Gravité du monde.
Definition at line 29 of file PhysicWorld.cpp.
void PhysicWorld::initGround (const char * filename)
Méthode permettant de créer un terrain (objet rigide de masse nulle selon le moteur physique Bullet) à partir d'une meshe WaveFrontObject (.obj).
Parameters:
[filename] : Chemin absolu de la meshe.
Bug:
Le moteur physique Bullet impose des objets rigides de moins de 50 faces. Le problème est au niveau de l'approximation de la meshe qui n'est pas satisfaisant.
Definition at line 34 of file PhysicWorld.cpp.
Referenced by GLTetraRendering::initPhysics().
void PhysicWorld::setGravite (const btVector3 & newGravite)
setter permettant d'affecter au monde une nouvelle gravitée, remplacant l'ancienne.
Parameters:
[newGravite] : vecteur définissant la nouvelle gravitée à appliquer.
Definition at line 23 of file PhysicWorld.cpp.
The documentation for this class was generated from the following files:
PhysicWorld.h
PhysicWorld.cpp