TetraBot: PhysicPiston Class Reference
PhysicPiston Class Reference
Cette classe représente un piston définit par deux extrémitées liées entre eux par une contrainte linéaire. Le piston modifie son étirement par le biais d'un moteur.
#include <PhysicPiston.h>
Public Member Functions
PhysicPiston (btDynamicsWorld *ownerWorld, Ogre::SceneNode *nodeOgre, const btVector3 &positionOffset, btScalar min, btScalar max, btScalar vitesse)
Constructeur de la classe PhysicPiston en relation avec le moteur graphique Ogre.
~PhysicPiston ()
Destructeur.
btVector3 getCenterOfMassPosition ()
Méthode calculant le centre de masse du piston (surcharge de la classe Composant). Le centre de masse est le milieu des centres de masses des extrémitées du piston.
btSliderConstraint * getContrainte ()
getter
void setContrainte (btSliderConstraint *constraint)
setter
btRigidBody * getBodyA ()
getter
void setBodyA (btRigidBody *body)
setter
btRigidBody * getBodyB ()
getter
void setBodyB (btRigidBody *body)
setter
btBoxShape * getShapeA ()
getter
void setShapeA (btBoxShape *newShape)
setter
btBoxShape * getShapeB ()
getter
void setShapeB (btBoxShape *newShape)
setter
btScalar getTailleMin ()
getter
btScalar getTailleMax ()
getter
void setTailleMin (btScalar tailleVoulu)
setter
void setTailleMax (btScalar tailleVoulu)
setter
btConeTwistConstraint * getConeA ()
getter
btConeTwistConstraint * getConeB ()
getter
void setConeA (btConeTwistConstraint *contrainteConique)
setter
void setConeB (btConeTwistConstraint *contrainteConique)
setter
btScalar getLength ()
Méthode calculant la taille courante du piston.
int actionnerEdge (btScalar tailleVoulu)
Méthode permettant de changer la taille du piston.
void lock ()
Méthode blocquant le piston à sa taille courante.
void unlock ()
Méthode déblocquant le piston.
void translate (const btVector3 &to)
Méthode effectuant une translation du piston (translation effectuée sur chacune des deux extrémitées).
Protected Attributes
btScalar tailleMin
btScalar tailleMax
btScalar velocite
bool estBloque
btBoxShape * shapeA
btBoxShape * shapeB
btRigidBody * bodyA
btRigidBody * bodyB
btSliderConstraint * contrainte
btConeTwistConstraint * coneA
btConeTwistConstraint * coneB
Detailed Description
Cette classe représente un piston définit par deux extrémitées liées entre eux par une contrainte linéaire. Le piston modifie son étirement par le biais d'un moteur.
Definition at line 25 of file PhysicPiston.h.
Constructor & Destructor Documentation
PhysicPiston::PhysicPiston (btDynamicsWorld * ownerWorld, Ogre::SceneNode * nodeOgre, const btVector3 & positionOffset, btScalar min, btScalar max, btScalar vitesse)
Constructeur de la classe PhysicPiston en relation avec le moteur graphique Ogre.
Constructeur de la classe PhysicPiston.
Parameters:
[ownerWorld] : description du monde physique selon le moteur Bullet auquel le composant sera soumis.
[nodeOgre] : noeud de scène d'Ogre représentant grapghiquement le piston.
[positionOffset] : position initiale du piston.
[min] : longueur minimale du piston.
[max] : longueur maximale du piston.
[vitesse] : vitesse du moteur dupiston.
[ownerWorld] : description du monde physique selon le moteur Bullet auquel le composant sera soumis.
[positionOffset] : position initiale du piston.
[min] : longueur minimale du piston.
[max] : longueur maximale du piston.
[vitesse] : vitesse du moteur dupiston.
Definition at line 9 of file PhysicPiston.cpp.
References bodyA, bodyB, coneA, coneB, contrainte, CUBE_SIZE, EDGE_STRENGTH, EDGE_WEIGHT, PhysicComponent::localCreateRigidBody(), shapeA, shapeB, and PhysicComponent::World.
Member Function Documentation
int PhysicPiston::actionnerEdge (btScalar tailleVoulu) [virtual]
Méthode permettant de changer la taille du piston.
Parameters:
[tailleVoulu] : taille souhaitée.
Returns:
Une valeur différente de zéro signifie un disfonctionnement du piston.
Implements PhysicEdge.
Definition at line 280 of file PhysicPiston.cpp.
References contrainte, EDGE_WAIT, getLength(), lock(), tailleMax, tailleMin, unlock(), and velocite.
Referenced by ActionPiston::execute().
btRigidBody * PhysicPiston::getBodyA ()
getter
Returns:
Objet rigide représentant l'extrémitée A du piston.
Definition at line 130 of file PhysicPiston.cpp.
References bodyA.
Referenced by PhysicNoeud::linkEdge().
btRigidBody * PhysicPiston::getBodyB ()
getter
Returns:
Objet rigide représentant l'extrémitée B du piston.
Definition at line 134 of file PhysicPiston.cpp.
References bodyB.
Referenced by PhysicNoeud::linkEdge().
btVector3 PhysicPiston::getCenterOfMassPosition () [virtual]
Méthode calculant le centre de masse du piston (surcharge de la classe Composant). Le centre de masse est le milieu des centres de masses des extrémitées du piston.
Returns:
Centre de masse du piston.
Implements PhysicComponent.
Definition at line 125 of file PhysicPiston.cpp.
References bodyA, and bodyB.
btConeTwistConstraint * PhysicPiston::getConeA ()
getter
Returns:
contrainte conique liant l'extrémitée A du piston à un sommet (classe Vertex) ou NULL si la liaison n'a pas encore été effectuée.
Definition at line 335 of file PhysicPiston.cpp.
References coneA.
Referenced by RobotWheels::RobotWheels().
btConeTwistConstraint * PhysicPiston::getConeB ()
getter
Returns:
contrainte conique liant l'extrémitée B du piston à un sommet (classe Vertex) ou NULL si la liaison n'a pas encore été effectuée.
Definition at line 339 of file PhysicPiston.cpp.
References coneB.
Referenced by RobotWheels::RobotWheels().
btSliderConstraint * PhysicPiston::getContrainte ()
getter
Returns:
Contrainte linéaire liant les deux extrémitées du piston.
Definition at line 162 of file PhysicPiston.cpp.
References contrainte.
Referenced by GLTetraRendering::clientMoveAndDisplay(), and GLTetraRendering::displayCallback().
btScalar PhysicPiston::getLength ()
Méthode calculant la taille courante du piston.
Méthode retournant le statut du piston.
Returns:
taille courante du piston.
True si le piston est bloqué, False dans le cas contraire.
Definition at line 191 of file PhysicPiston.cpp.
References bodyA, and bodyB.
Referenced by actionnerEdge(), RobotTetra::Deplacement(), lock(), RobotTetra::maxiRobot(), and RobotTetra::nanoRobot().
btBoxShape * PhysicPiston::getShapeA ()
getter
Returns:
Forme de l'extrémitée A du piston.
Definition at line 146 of file PhysicPiston.cpp.
References shapeA.
Referenced by PhysicNoeud::linkEdge().
btBoxShape * PhysicPiston::getShapeB ()
getter
Returns:
Forme de l'extrémitée A du piston.
Definition at line 150 of file PhysicPiston.cpp.
References shapeB.
Referenced by PhysicNoeud::linkEdge().
btScalar PhysicPiston::getTailleMax ()
getter
Returns:
Taille maximale du piston.
Definition at line 174 of file PhysicPiston.cpp.
References tailleMax.
Referenced by RobotTetra::Deplacement(), ControleurRobot::execute(), RobotTetra::marcherRobot(), and RobotTetra::maxiRobot().
btScalar PhysicPiston::getTailleMin ()
getter
Returns:
Taille minimale du piston.
Definition at line 170 of file PhysicPiston.cpp.
References tailleMin.
Referenced by RobotTetra::Deplacement(), ControleurRobot::execute(), RobotTetra::marcherRobot(), and RobotTetra::nanoRobot().
void PhysicPiston::setBodyA (btRigidBody * body)
setter
Parameters:
[body] : nouvel objet rigide pour définir l'extrémitée A du piston.
Deprecated:
L'objet rigide se crée dans le constructeur.
Definition at line 138 of file PhysicPiston.cpp.
References bodyA.
void PhysicPiston::setBodyB (btRigidBody * body)
setter
Parameters:
[body] : nouvel objet rigide pour définir l'extrémitée B du piston.
Deprecated:
L'objet rigide se crée dans le constructeur.
Definition at line 142 of file PhysicPiston.cpp.
References bodyB.
void PhysicPiston::setConeA (btConeTwistConstraint * contrainteConique)
setter
Parameters:
[contrainteConique] : contrainte conique liant l'extrémitée A du piston à un sommet (classe Vertex).
Definition at line 343 of file PhysicPiston.cpp.
References coneA.
Referenced by PhysicNoeud::linkEdge().
void PhysicPiston::setConeB (btConeTwistConstraint * contrainteConique)
setter
Parameters:
[contrainteConique] : contrainte conique liant l'extrémitée B du piston à un sommet (classe Vertex).
Definition at line 347 of file PhysicPiston.cpp.
References coneB.
Referenced by PhysicNoeud::linkEdge().
void PhysicPiston::setContrainte (btSliderConstraint * constraint)
setter
Parameters:
[constraint] : nouvelle contrainte à appliquer sur le piston.
Deprecated:
La contrainte linéaire du piston est créée dans le constructeur.
Definition at line 166 of file PhysicPiston.cpp.
References contrainte.
void PhysicPiston::setShapeA (btBoxShape * newShape)
setter
Parameters:
[newShape] : nouvelle forme de l'objet représentant l'extrémitée A du piston.
Deprecated:
La forme de l'extrémitée A du piston est créée dans le constructeur.
Definition at line 154 of file PhysicPiston.cpp.
References shapeA.
void PhysicPiston::setShapeB (btBoxShape * newShape)
setter
Parameters:
[newShape] : nouvelle forme de l'objet représentant l'extrémitée B du piston.
Deprecated:
La forme de l'extrémitée B du piston est créée dans le constructeur.
Definition at line 158 of file PhysicPiston.cpp.
References shapeB.
void PhysicPiston::setTailleMax (btScalar tailleVoulu)
setter
Parameters:
[tailleVoulu] : nouvelle taille maximale du piston.
Definition at line 184 of file PhysicPiston.cpp.
References contrainte, and tailleMax.
void PhysicPiston::setTailleMin (btScalar tailleVoulu)
setter
Parameters:
[tailleVoulu] : nouvelle taille minimale du piston.
Definition at line 178 of file PhysicPiston.cpp.
References contrainte, and tailleMin.
void PhysicPiston::translate (const btVector3 & to) [virtual]
Méthode effectuant une translation du piston (translation effectuée sur chacune des deux extrémitées).
Parameters:
[to] : point représentant la destination du centre de masse du piston. Une fois la méthode exécutée, le centre de masse du piston sera situé au point [to].
Implements PhysicComponent.
Definition at line 352 of file PhysicPiston.cpp.
References bodyA, and bodyB.
Member Data Documentation
btRigidBody* PhysicPiston::bodyA [protected]
bodyA : objet rigide représentant l'extrémitée A du piston.
Definition at line 42 of file PhysicPiston.h.
Referenced by getBodyA(), getCenterOfMassPosition(), getLength(), PhysicPiston(), setBodyA(), translate(), and ~PhysicPiston().
btRigidBody* PhysicPiston::bodyB [protected]
bodyB : objet rigide représentant l'extrémitée B du piston.
Definition at line 43 of file PhysicPiston.h.
Referenced by getBodyB(), getCenterOfMassPosition(), getLength(), PhysicPiston(), setBodyB(), translate(), and ~PhysicPiston().
btConeTwistConstraint* PhysicPiston::coneA [protected]
coneA : contrainte conique liant l'extrémitée A du piston à un sommet (classe Vertex).
Definition at line 49 of file PhysicPiston.h.
Referenced by getConeA(), PhysicPiston(), and setConeA().
btConeTwistConstraint* PhysicPiston::coneB [protected]
coneB : contrainte conique liant l'extrémitée B du piston à un sommet (classe Vertex).
Definition at line 50 of file PhysicPiston.h.
Referenced by getConeB(), PhysicPiston(), and setConeB().
btSliderConstraint* PhysicPiston::contrainte [protected]
contrainte : contrainte liant les deux extrémitées du piston.
Definition at line 46 of file PhysicPiston.h.
Referenced by actionnerEdge(), getContrainte(), lock(), PhysicPiston(), setContrainte(), setTailleMax(), setTailleMin(), unlock(), and ~PhysicPiston().
bool PhysicPiston::estBloque [protected]
estBloque : booléen indicant si le piston est bloqué ou non.
Definition at line 35 of file PhysicPiston.h.
Referenced by lock(), and unlock().
btBoxShape* PhysicPiston::shapeA [protected]
shapeA : forme de l'extrémitée A du piston.
Definition at line 38 of file PhysicPiston.h.
Referenced by getShapeA(), PhysicPiston(), setShapeA(), and ~PhysicPiston().
btBoxShape* PhysicPiston::shapeB [protected]
shapeB : forme de l'extrémitée B du piston.
Definition at line 39 of file PhysicPiston.h.
Referenced by getShapeB(), PhysicPiston(), setShapeB(), and ~PhysicPiston().
btScalar PhysicPiston::tailleMax [protected]
tailleMax : longueur maximale du piston.
Definition at line 31 of file PhysicPiston.h.
Referenced by actionnerEdge(), getTailleMax(), setTailleMax(), and unlock().
btScalar PhysicPiston::tailleMin [protected]
tailleMin : longueur minimale du piston.
Definition at line 29 of file PhysicPiston.h.
Referenced by actionnerEdge(), getTailleMin(), setTailleMin(), and unlock().
btScalar PhysicPiston::velocite [protected]
velocite : vitesse du piston.
Definition at line 33 of file PhysicPiston.h.
Referenced by actionnerEdge().
The documentation for this class was generated from the following files:
PhysicPiston.h
PhysicPiston.cpp