TetraBot: PhysicNoeud Class Reference
PhysicNoeud Class Reference
Représentation d'un noeud de robot. Ce noeud peut avoir n'importe quelle forme, mais est constitué d'un seul objet(rigide) physique.
#include <PhysicNoeud.h>
Public Member Functions
PhysicNoeud (btDynamicsWorld *ownerWorld, Ogre::SceneNode *nodeOgre, btConvexInternalShape *forme, const btVector3 &offset, btScalar masse)
Constructeur de la classe PhysicNoeud en relation avec le moteur graphique Ogre.
PhysicNoeud (btDynamicsWorld *ownerWorld, btConvexInternalShape *forme, const btVector3 &offset, btScalar masse)
Constructeur de la classe PhysicNoeud.
~PhysicNoeud ()
Destructeur.
btVector3 getCenterOfMassPosition ()
Méthode calculant le centre de masse du noeud (surcharge de la classe Composant). Le centre de masse est le centre de masse de l'objet physique.
btRigidBody * getBody ()
getter
void setBody (btRigidBody *body)
setter
btConvexInternalShape * getShapeNoeud ()
getter
void setShapeNoeud (btConvexInternalShape *shape)
setter
int linkEdge (PhysicEdge *edge, char extremitee, btScalar rotationY, btScalar rotationZ)
Méthode permettant de lier au noeud un arc. Deux attributs décrivent deux angles permettant de faire une rotation autour du noeud. Ainsi on peut lier l'arc à n'importe quel point de la surface du noeud. Il est à noter que l'on effectue une rotation suivant l'axe Y en premier, puis suivant l'axe Z.
void translate (const btVector3 &to)
Méthode effectuant une translation du noeud.
Protected Attributes
btConvexInternalShape * shapeNoeud
btRigidBody * bodyNoeud
Detailed Description
Représentation d'un noeud de robot. Ce noeud peut avoir n'importe quelle forme, mais est constitué d'un seul objet(rigide) physique.
Definition at line 23 of file PhysicNoeud.h.
Constructor & Destructor Documentation
PhysicNoeud::PhysicNoeud (btDynamicsWorld * ownerWorld, Ogre::SceneNode * nodeOgre, btConvexInternalShape * forme, const btVector3 & offset, btScalar masse)
Constructeur de la classe PhysicNoeud en relation avec le moteur graphique Ogre.
Parameters:
[ownerWorld] : description du monde physique selon le moteur Bullet auquel le composant sera soumis.
[nodeOgre] : noeud de scène d'Ogre représentant grapghiquement le noeud.
[forme] : forme souhaité que le noeud doit avoir selon le moteur physique Bullet.
[positionOffset] : position initiale du noeud.
[masse] : poids du noeud.
Definition at line 11 of file PhysicNoeud.cpp.
References bodyNoeud, PhysicComponent::localCreateRigidBody(), RUBDOWN, and shapeNoeud.
PhysicNoeud::PhysicNoeud (btDynamicsWorld * ownerWorld, btConvexInternalShape * forme, const btVector3 & offset, btScalar masse)
Constructeur de la classe PhysicNoeud.
Parameters:
[ownerWorld] : description du monde physique selon le moteur Bullet auquel le composant sera soumis.
[forme] : forme souhaité que le noeud doit avoir selon le moteur physique Bullet.
[positionOffset] : position initiale du noeud.
[masse] : poids du noeud.
Definition at line 31 of file PhysicNoeud.cpp.
References bodyNoeud, PhysicComponent::localCreateRigidBody(), RUBDOWN, shapeNoeud, and PhysicComponent::World.
Member Function Documentation
btRigidBody * PhysicNoeud::getBody ()
getter
Returns:
Objet rigide représentant le noeud.
Definition at line 63 of file PhysicNoeud.cpp.
References bodyNoeud.
Referenced by GLTetraRendering::keyboardCallback().
btVector3 PhysicNoeud::getCenterOfMassPosition () [virtual]
Méthode calculant le centre de masse du noeud (surcharge de la classe Composant). Le centre de masse est le centre de masse de l'objet physique.
Returns:
Centre de masse du noeud.
Implements PhysicComponent.
Definition at line 57 of file PhysicNoeud.cpp.
References bodyNoeud.
Referenced by RobotTetra::marcherRobot().
btConvexInternalShape * PhysicNoeud::getShapeNoeud ()
getter
Returns:
Forme du noeud selon le moteur physique Bullet.
Definition at line 73 of file PhysicNoeud.cpp.
References shapeNoeud.
int PhysicNoeud::linkEdge (PhysicEdge * edge, char extremitee, btScalar rotationY, btScalar rotationZ) [virtual]
Méthode permettant de lier au noeud un arc. Deux attributs décrivent deux angles permettant de faire une rotation autour du noeud. Ainsi on peut lier l'arc à n'importe quel point de la surface du noeud. Il est à noter que l'on effectue une rotation suivant l'axe Y en premier, puis suivant l'axe Z.
Parameters:
[edge] : arc à lier au noeud. \ [extremitee] : charactère désignant une des extrémitées de l'arc à lier. \ [rotationY] : angle en radian de rotation autour de l'axe Y. \ [rotationZ] : angle en radian de rotation autour de l'axe Z.
Implements PhysicVertex.
Definition at line 84 of file PhysicNoeud.cpp.
References bodyNoeud, CONE_ANGLE, PhysicPiston::getBodyA(), PhysicPiston::getBodyB(), PhysicPiston::getShapeA(), PhysicPiston::getShapeB(), M_PI, PhysicPiston::setConeA(), PhysicPiston::setConeB(), shapeNoeud, and PhysicComponent::World.
void PhysicNoeud::setBody (btRigidBody * body)
setter
Parameters:
[body] : nouveau objet représentant le noeud.
Deprecated:
La création de l'objet rigide s'effectue dans le constructeur.
Definition at line 68 of file PhysicNoeud.cpp.
References bodyNoeud.
void PhysicNoeud::setShapeNoeud (btConvexInternalShape * shape)
setter
Parameters:
[shape] : nouvelle forme du noeud.
Definition at line 78 of file PhysicNoeud.cpp.
References shapeNoeud.
void PhysicNoeud::translate (const btVector3 & to) [virtual]
Méthode effectuant une translation du noeud.
Parameters:
[to] : point représentant la destination du centre de masse du noeud. Une fois la méthode exécutée, le centre de masse du noeud sera situé au point [to].
Implements PhysicComponent.
Definition at line 164 of file PhysicNoeud.cpp.
References bodyNoeud.
Member Data Documentation
btRigidBody* PhysicNoeud::bodyNoeud [protected]
bodyNoeud : objet rigide d'un noeud selon le moteur physique Bullet.
Definition at line 29 of file PhysicNoeud.h.
Referenced by getBody(), getCenterOfMassPosition(), linkEdge(), PhysicNoeud(), setBody(), translate(), and ~PhysicNoeud().
btConvexInternalShape* PhysicNoeud::shapeNoeud [protected]
shapeNoeud : forme d'un noeud selon le moteur physique Bullet.
Definition at line 27 of file PhysicNoeud.h.
Referenced by getShapeNoeud(), linkEdge(), PhysicNoeud(), setShapeNoeud(), and ~PhysicNoeud().
The documentation for this class was generated from the following files:
PhysicNoeud.h
PhysicNoeud.cpp