TetraBot: RobotTetra Class Reference
RobotTetra Class Reference
Classe créant un robot tétrahédrique composé de noeuds sphériques et de pistons.
#include <RobotTetra.h>
Public Member Functions
btVector3 getCenterOfMassPosition ()
Méthode calculant le centre de masse du robot.
bool IsNotInArea (const btVector3 &G, const btVector3 &end2)
Détermine si les deux points sont distant d'au moins 5 unitées de mesure.
void nanoRobot ()
Methode réduisant au minimum la longueur des pistons du robot.
void maxiRobot ()
Méthode étirant au maximum la longueur des pistons du robot.
void translate (const btVector3 &to)
Permet de faire une translation sur le robot.
void Deplacement (unsigned char key)
Déplace le robot en fonction de la touche appuyée passée en paramètre. Les déplacements peuvent être locaux (etirement d'un piston) ou généraux (déplacement de toute la structure vers un point).
Static Public Member Functions
static void * marcherRobot (void *demo)
Méthode utilisée par un thread pour déplacer le robot. Le robot se déplace tant que la méthode IsNotInArea est vraie.
Public Attributes
btRigidBody * bodyCube
Detailed Description
Classe créant un robot tétrahédrique composé de noeuds sphériques et de pistons.
Definition at line 28 of file RobotTetra.h.
Member Function Documentation
void RobotTetra::Deplacement (unsigned char key)
Déplace le robot en fonction de la touche appuyée passée en paramètre. Les déplacements peuvent être locaux (etirement d'un piston) ou généraux (déplacement de toute la structure vers un point).
Parameters:
[key] : touche appuyée.
Definition at line 4 of file RobotTetra.cpp.
References PhysicRobot::Arcs, getCenterOfMassPosition(), PhysicPiston::getLength(), PhysicPiston::getTailleMax(), PhysicPiston::getTailleMin(), and PhysicRobot::Sommets.
Referenced by GLTetraRendering::keyboardCallback().
btVector3 RobotTetra::getCenterOfMassPosition () [virtual]
Méthode calculant le centre de masse du robot.
Returns:
Centre de masse du robot.
Implements PhysicRobot.
Definition at line 554 of file RobotTetra.cpp.
References PhysicRobot::Sommets.
Referenced by Deplacement(), marcherRobot(), and translate().
bool RobotTetra::IsNotInArea (const btVector3 & G, const btVector3 & end2)
Détermine si les deux points sont distant d'au moins 5 unitées de mesure.
Parameters:
[G] : Premier point.
[end2] : Second point.
Returns:
Vrai si la distance est supérieur à 5. Faux sinon.
Definition at line 201 of file RobotTetra.cpp.
Referenced by marcherRobot().
static void * RobotTetra::marcherRobot (void * demo) [static]
Méthode utilisée par un thread pour déplacer le robot. Le robot se déplace tant que la méthode IsNotInArea est vraie.
Parameters:
[demo] : Instance de la classe RobotTetra à manipuler.
Returns:
NULL.
Definition at line 253 of file RobotTetra.cpp.
References action, PhysicRobot::Arcs, bodyCube, end, PhysicNoeud::getCenterOfMassPosition(), getCenterOfMassPosition(), PhysicComponent::getID(), PhysicPiston::getTailleMax(), PhysicPiston::getTailleMin(), IsNotInArea(), PhysicPiston::lock(), ActionPiston::setPiston(), ActionPiston::setTailleVoulue(), PhysicRobot::Sommets, and PhysicPiston::unlock().
Referenced by GLTetraRendering::specialKeyboard().
void RobotTetra::translate (const btVector3 & to) [virtual]
Permet de faire une translation sur le robot.
Parameters:
[to] : point représentant la destination du robot. Une fois la méthode exécutée, le centre de masse du robot sera situé au point [to].
Implements PhysicRobot.
Definition at line 567 of file RobotTetra.cpp.
References getCenterOfMassPosition(), and PhysicRobot::Sommets.
Member Data Documentation
btRigidBody* RobotTetra::bodyCube
< action : Tableau d'Action utilisées par les pistons du robot.
Definition at line 35 of file RobotTetra.h.
Referenced by marcherRobot(), and GLTetraRendering::specialKeyboard().
The documentation for this class was generated from the following files:
RobotTetra.h
RobotTetra.cpp